apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "log-aggregation-system.fullname" . }}
  labels:
    {{- include "log-aggregation-system.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  LOG_FORMAT: {{ .Values.config.logFormat | quote }}
  OTEL_ENABLED: {{ .Values.config.otelEnabled | quote }}
  OTEL_SERVICE_NAME: {{ .Values.config.otelServiceName | quote }}
  STORAGE_BACKEND: {{ .Values.config.storageBackend | quote }}
  ELASTICSEARCH_INDEX: {{ .Values.config.elasticsearchIndex | quote }}
